extends Node
## Testi del gioco in italiano e inglese: chiave -> [it, en].

const STR := {
	# --- menu
	"title": ["IL SOGNATORE", "THE DREAMER"],
	"subtitle": ["Un sogno lungo una vita", "A dream as long as a life"],
	"continue": ["Continua", "Continue"],
	"new_game": ["Nuova partita", "New game"],
	"gallery": ["Galleria", "Gallery"],
	"settings": ["Impostazioni", "Settings"],
	"credits": ["Crediti", "Credits"],
	"next": ["Avanti", "Next"],
	"set_hd2d": ["Livelli in 3D", "3D levels"],
	"set_smooth": ["Grafica levigata", "Smooth graphics"],
	"mod_title": ["Mod menu", "Mod menu"],
	"mod_god": ["Immortalità", "Immortality"],
	"mod_unlock": ["Sblocca tutto", "Unlock everything"],
	"mod_unlock_d": ["Livelli, galleria, bestiario,\nricordi e modalità Incubo.", "Levels, gallery, bestiary,\nmemories and Nightmare mode."],
	"mod_finale": ["Vai al finale", "Go to the ending"],
	"back": ["Indietro", "Back"],
	"play": ["Gioca", "Play"],
	"yes": ["Sì", "Yes"],
	"no": ["No", "No"],
	"on": ["sì", "on"],
	"off": ["no", "off"],
	"slot": ["Slot", "Slot"],
	"empty": ["vuoto", "empty"],
	"choose_slot": ["Scegli uno slot", "Choose a slot"],
	"overwrite": ["Sovrascrivere questa partita?", "Overwrite this game?"],
	"ended": ["partita finita", "game over"],
	"finished": ["gioco finito", "completed"],
	"mode": ["Modalità", "Mode"],
	"mode_lucido": ["Sogno lucido", "Lucid dream"],
	"mode_agitato": ["Sonno agitato", "Restless sleep"],
	"mode_incubo": ["Incubo", "Nightmare"],
	"mode_lucido_d": ["Vite infinite. Riparti dal checkpoint.", "Infinite lives. Restart from checkpoint."],
	"mode_agitato_d": ["5 vite. Se finiscono, ti svegli:\nriparti dall'inizio del mondo.", "5 lives. Lose them all and you wake up:\nrestart from the start of the world."],
	"mode_incubo_d": ["Una sola vita. Alla prima morte\nla partita finisce.", "One life. The first death\nends the game."],
	"mode_locked": ["Si sblocca finendo il gioco.", "Unlocked by finishing the game."],
	"seed": ["Seed", "Seed"],
	"seed_random": ["Casuale", "Random"],
	"seed_manual": ["Inserisci", "Enter"],
	"seed_hint": ["Stesso seed = stessi livelli di un amico.", "Same seed = same levels as a friend."],
	"skip_tut": ["Salta il tutorial", "Skip tutorial"],
	"start_dream": ["Inizia a sognare", "Start dreaming"],
	"generating": ["Sto sognando i mondi...", "Dreaming up the worlds..."],
	"ok": ["OK", "OK"],
	"delete": ["Canc", "Del"],
	# --- gioco
	"pause": ["Pausa", "Paused"],
	"resume": ["Riprendi", "Resume"],
	"restart_cp": ["Ricomincia dal checkpoint", "Restart from checkpoint"],
	"to_map": ["Torna alla mappa", "Back to map"],
	"quit_title": ["Esci", "Quit"],
	"level_done": ["Livello completato!", "Level complete!"],
	"fragments": ["Frammenti", "Fragments"],
	"secret": ["Oggetto segreto", "Secret object"],
	"found": ["trovato!", "found!"],
	"not_found": ["non trovato", "not found"],
	"time": ["Tempo", "Time"],
	"record": ["Record!", "Record!"],
	"best": ["Miglior tempo", "Best time"],
	"wake_title": ["Ti svegli...", "You wake up..."],
	"wake_text": ["Il sogno ricomincia\ndall'inizio del mondo.", "The dream starts again\nfrom the beginning of the world."],
	"over_title": ["L'incubo finisce qui", "The nightmare ends here"],
	"over_text": ["Una sola vita. Restano i ricordi.", "One life only. The memories remain."],
	"deaths": ["Cadute", "Deaths"],
	"level": ["Livello", "Level"],
	"boss": ["Boss", "Boss"],
	"locked": ["bloccato", "locked"],
	"secrets_n": ["Segreti", "Secrets"],
	"say_life": ["Una vita in più!", "An extra life!"],
	"say_secret": ["Un ricordo di noi!", "A memory of us!"],
	"say_careful": ["Attento a non cadere!", "Careful, don't fall!"],
	"say_boss": ["Usa la tua abilità!", "Use your ability!"],
	"skip": ["Salta", "Skip"],
	# --- impostazioni
	"set_music": ["Musica", "Music"],
	"set_sfx": ["Effetti", "Sound"],
	"set_vibra": ["Vibrazione", "Vibration"],
	"set_lefty": ["Mancini", "Left-handed"],
	"set_joy_size": ["Joystick", "Joystick"],
	"set_joy_alpha": ["Opacità comandi", "Controls opacity"],
	"set_lang": ["Lingua", "Language"],
	"set_cb": ["Daltonismo", "Colour-blind"],
	"set_reduce": ["Riduci lampi", "Reduce flashes"],
	"set_speed": ["Velocità", "Speed"],
	"set_auto_high": ["Salto alto auto", "Auto high jump"],
	"set_big_text": ["Fumetti grandi", "Big bubbles"],
	"set_cues": ["Avvisi visivi", "Visual cues"],
	"cb_0": ["no", "off"],
	"cb_1": ["protanopia", "protanopia"],
	"cb_2": ["deuteranopia", "deuteranopia"],
	"cb_3": ["tritanopia", "tritanopia"],
	# --- galleria
	"gal_story": ["Storia", "Story"],
	"gal_memories": ["Ricordi", "Memories"],
	"gal_bestiary": ["Bestiario", "Bestiary"],
	"gal_stats": ["Statistiche", "Stats"],
	"gal_time": ["Tempo di gioco", "Play time"],
	"gal_finished": ["Sogni completati", "Dreams completed"],
	"gal_none": ["Ancora niente qui.", "Nothing here yet."],
	"credits_text": [
		"IL SOGNATORE\n\nIdea e design\nFlavio Ceccarelli\n\nProgrammazione\nFlavio Ceccarelli\n\nGrafica e audio\nOriginali per Il Sognatore\n\nMotore\nGodot Engine 4 (licenza MIT)\n\nA Chiara,\nl'amore della mia vita\ne la mia migliore amica.\n\nGrazie per aver sognato con me.",
		"THE DREAMER\n\nConcept and design\nFlavio Ceccarelli\n\nProgramming\nFlavio Ceccarelli\n\nGraphics and audio\nOriginal to The Dreamer\n\nEngine\nGodot Engine 4 (MIT licence)\n\nTo Chiara,\nthe love of my life\nand my best friend.\n\nThank you for dreaming with me."],
	# --- mondi
	"world_1": ["La Cameretta", "The Bedroom"],
	"world_2": ["Prati di Nuvole", "Cloud Meadows"],
	"world_3": ["Biblioteca Infinita", "Endless Library"],
	"world_4": ["Oceano di Stelle", "Ocean of Stars"],
	"world_5": ["Città Capovolta", "Upside-Down City"],
	"world_6": ["L'Orologeria", "The Clockworks"],
	"world_7": ["Regno dei Dolci", "Candy Kingdom"],
	"world_8": ["Sala degli Specchi", "Hall of Mirrors"],
	"world_9": ["La Tempesta", "The Storm"],
	"world_10": ["L'Incubo", "The Nightmare"],
	"boss_1": ["Re dei Giocattoli", "Toy King"],
	"boss_2": ["Il Cumulonembo", "The Thunderhead"],
	"boss_3": ["Il Grande Tomo", "The Great Tome"],
	"boss_4": ["Il Leviatano di Stelle", "Star Leviathan"],
	"boss_5": ["Il Sindaco Sottosopra", "The Upside-Down Mayor"],
	"boss_6": ["Il Grande Orologio", "The Great Clock"],
	"boss_7": ["La Regina Glassata", "The Frosted Queen"],
	"boss_8": ["Flavio Oscuro", "Dark Flavio"],
	"boss_9": ["L'Occhio del Ciclone", "Eye of the Cyclone"],
	"boss_10": ["L'Incubo", "The Nightmare"],
	# --- abilità
	"abn_doppio_salto": ["Doppio salto", "Double jump"],
	"abn_scatto": ["Scatto", "Dash"],
	"abn_bolla": ["Bolla di sogno", "Dream bubble"],
	"abn_gravita": ["Inversione di gravità", "Gravity flip"],
	"abn_tempo": ["Rallenta il tempo", "Slow time"],
	"abn_schianto": ["Schianto", "Slam"],
	"abn_riflesso": ["Riflesso", "Reflection"],
	"abn_planata": ["Planata", "Glide"],
	"abn_selettore": ["Tutte le abilità", "All abilities"],
	"new_ability": ["Nuova abilità", "New ability"],
	# --- nemici
	"en_soldatino": ["Soldatino di piombo", "Tin soldier"],
	"en_pallina": ["Pallina", "Bouncy ball"],
	"en_trottola": ["Trottola", "Spinning top"],
	"en_pecora": ["Pecora-nuvola", "Cloud sheep"],
	"en_nuvoletta": ["Nuvoletta", "Storm puff"],
	"en_grandine": ["Chicco di grandine", "Hailstone"],
	"en_libro": ["Libro mordace", "Biting book"],
	"en_segnalibro": ["Segnalibro", "Bookmark"],
	"en_calamaio": ["Calamaio", "Inkwell"],
	"en_medusa": ["Medusa cometa", "Comet jelly"],
	"en_pesce": ["Pesce lanterna", "Lantern fish"],
	"en_stella": ["Stella cadente", "Shooting star"],
	"en_lampione": ["Lampione", "Street lamp"],
	"en_piccione": ["Piccione al contrario", "Upside-down pigeon"],
	"en_tombino": ["Tombino", "Manhole"],
	"en_ingranaggio": ["Ingranaggio", "Cog"],
	"en_cucu": ["Cucù", "Cuckoo"],
	"en_pendolo": ["Pendolo", "Pendulum"],
	"en_gommoso": ["Gommoso", "Gummy"],
	"en_cupcake": ["Cupcake", "Cupcake"],
	"en_caramella": ["Caramella appiccicosa", "Sticky candy"],
	"en_vetro": ["Frammento di vetro", "Glass shard"],
	"en_riflesso_oscuro": ["Riflesso oscuro", "Dark reflection"],
	"en_specchio": ["Specchio deformante", "Warping mirror"],
	"en_raffica": ["Raffica", "Gust"],
	"en_corvo": ["Corvo", "Crow"],
	"en_ombrello": ["Ombrello rotto", "Broken umbrella"],
	"en_ombra": ["Ombra", "Shadow"],
	"en_mano": ["Mano d'ombra", "Shadow hand"],
	"en_occhio": ["Occhio", "Eye"],
	# --- suggerimenti dell'eco (massimo 6 parole)
	"tut_move": ["Flavio! Seguimi!", "Flavio! Follow me!"],
	"tut_jump": ["Tocca a destra per saltare!", "Tap the right side to jump!"],
	"tut_high": ["Tieni premuto: salti più in alto!", "Hold it: you jump higher!"],
	"tut_frag": ["Raccogli i frammenti di sogno!", "Collect the dream fragments!"],
	"tut_cp": ["Qui il sogno si ricorda di te.", "Here the dream remembers you."],
	"tut_enemy": ["Saltagli in testa!", "Jump on its head!"],
	"tut_pit": ["Attento a non cadere!", "Careful, don't fall!"],
	"tut_secret": ["Qui c'è qualcosa...", "There's something here..."],
	"tut_end": ["Chiara è più avanti. Andiamo!", "Chiara is ahead. Let's go!"],
	"ab_doppio": ["Salta ancora, in aria!", "Jump again in mid-air!"],
	"ab_doppio2": ["Così arrivi più in alto.", "That gets you higher."],
	"ab_scatto": ["Scorri il dito: scatto!", "Swipe: dash!"],
	"ab_scatto2": ["Scatta sotto le soglie basse!", "Dash under low gaps!"],
	"ab_bolla": ["Scorri: una bolla di sogno!", "Swipe: a dream bubble!"],
	"ab_bolla2": ["Tocca per scoppiare la bolla.", "Tap to pop the bubble."],
	"ab_gravita": ["Scorri: tutto sottosopra!", "Swipe: upside down!"],
	"ab_gravita2": ["Cammina sul soffitto!", "Walk on the ceiling!"],
	"ab_tempo": ["Scorri: il tempo rallenta!", "Swipe: time slows down!"],
	"ab_tempo2": ["Passa mentre tutto è lento.", "Go while everything is slow."],
	"ab_schianto": ["In aria, scorri: schianto!", "In mid-air, swipe: slam!"],
	"ab_schianto2": ["Schiantati sul morbido: voli!", "Slam on soft ground: fly!"],
	"ab_riflesso": ["Scorri: il riflesso ti copia.", "Swipe: your reflection copies you."],
	"ab_riflesso2": ["Due interruttori: tu e lui.", "Two switches: you and him."],
	"ab_planata": ["Cadi e tieni premuto: plani!", "Fall and hold: you glide!"],
	"ab_planata2": ["Le correnti ti portano su.", "Updrafts carry you up."],
	"ab_selettore": ["Tocca l'icona: cambi abilità.", "Tap the icon: switch ability."],
	"ab_selettore2": ["Tieni premuto: la ruota.", "Hold it: the wheel."],
	# --- storia
	"prologue_1": ["Ogni sera Flavio e Chiara giocano in cameretta.\nLei è fatta di luce. Solo lui può vederla.", "Every night Flavio and Chiara play in the bedroom.\nShe is made of light. Only he can see her."],
	"prologue_2": ["Flavio si addormenta.\nUn'ombra entra nel sogno... e porta via Chiara.", "Flavio falls asleep.\nA shadow enters the dream... and takes Chiara away."],
	"prologue_3": ["Resta solo una scintilla: l'eco di Chiara.\n«Flavio! Seguimi!»", "Only a spark remains: Chiara's echo.\n\"Flavio! Follow me!\""],
	"after_1": ["Tra i giocattoli rotti, Flavio trova\nla ciliegia portafortuna di Chiara.\nL'eco brilla e punta verso il cielo.", "Among the broken toys, Flavio finds\nChiara's lucky cherry.\nThe echo glows and points to the sky."],
	"after_2": ["Flavio ha 9 anni e lo zaino in spalla.\nIl sogno diventa il primo giorno di scuola.", "Flavio is 9, backpack on his shoulders.\nThe dream becomes the first day of school."],
	"after_3": ["Dalla finestra della biblioteca\nsi vedono le stelle.\nFlavio decide di salire più in alto.", "From the library window\nyou can see the stars.\nFlavio decides to climb higher."],
	"after_4": ["Flavio ha 14 anni.\nIl mondo si capovolge,\ne l'eco inizia a sbiadire.", "Flavio is 14.\nThe world turns upside down,\nand the echo starts to fade."],
	"after_5": ["«Sono troppo grande\nper gli amici immaginari!»\nL'eco si spegne per un istante.", "\"I'm too old\nfor imaginary friends!\"\nThe echo goes out for a moment."],
	"after_6": ["Gli orologi corrono. Flavio ha 20 anni.\nIl tempo per giocare sembra finito.", "The clocks race. Flavio is 20.\nPlaytime seems to be over."],
	"after_7": ["Negli specchi Flavio vede\nsé stesso da bambino.\nIl bambino gli tende la mano.", "In the mirrors Flavio sees\nhimself as a child.\nThe child holds out his hand."],
	"after_8": ["Flavio ha 30 anni. L'eco è quasi invisibile.\nArriva una tempesta di paure da adulto.", "Flavio is 30. The echo is almost invisible.\nA storm of grown-up fears is coming."],
	"after_9": ["Oltre la tempesta, una porta.\nÈ la porta dell'Incubo.", "Beyond the storm, a door.\nIt is the Nightmare's door."],
	"finale_1": ["L'Incubo è sconfitto.\nMa Chiara è quasi trasparente.", "The Nightmare is defeated.\nBut Chiara is almost transparent."],
	"finale_2": ["«Chiara!»\nFlavio la chiama per nome.\nE lei torna a brillare.", "\"Chiara!\"\nFlavio calls her by name.\nAnd she shines again."],
	"finale_3": ["Flavio si sveglia. È adulto.\nAccanto al letto, un vecchio disegno di Chiara.\nE una lucina che si accende.", "Flavio wakes up. He is a grown man.\nBy the bed, an old drawing of Chiara.\nAnd a little light switching on."],
	"finale_4": ["Chiara è lì, accanto a lui.\nNon più fatta di luce: vera.\nFlavio si inginocchia. «Chiara, vuoi sposarmi?»", "Chiara is there, beside him.\nNo longer made of light: real.\nFlavio kneels. \"Chiara, will you marry me?\""],
	"epilogue": ["Flavio prende una matita e un foglio nuovo.\nDisegna Chiara. E accanto a lei, un bambino.\nCerti amori cominciano da bambini, e non finiscono più.", "Flavio takes a pencil and a fresh sheet.\nHe draws Chiara. And next to her, a child.\nSome loves begin in childhood, and never end."],
	"memory_1": ["Chiara nascondeva i giocattoli.\nFlavio li ritrovava sempre.", "Chiara used to hide the toys.\nFlavio always found them."],
	"memory_2": ["Sdraiati sul prato,\ndavano un nome a ogni nuvola.", "Lying on the grass,\nthey named every cloud."],
	"memory_3": ["Chiara inventava il finale\ndelle storie lasciate a metà.", "Chiara made up endings\nfor the stories left unfinished."],
	"memory_4": ["«Quante stelle ci sono?»\n«Una per ogni sogno.»", "\"How many stars are there?\"\n\"One for every dream.\""],
	"memory_5": ["A testa in giù sul divano,\nil mondo era più divertente.", "Upside down on the sofa,\nthe world was more fun."],
	"memory_6": ["«Ancora cinque minuti!»\nE Chiara fermava le lancette.", "\"Five more minutes!\"\nAnd Chiara stopped the clock hands."],
	"memory_7": ["Una caramella a testa.\nLa sua, Flavio la mangiava per lei.", "One sweet each.\nFlavio ate hers for her."],
	"memory_8": ["Allo specchio facevano le boccacce\nfinché non ridevano tutti e due.", "They pulled faces in the mirror\nuntil they both laughed."],
	"memory_9": ["Sotto la coperta, durante i temporali,\nChiara faceva luce.", "Under the blanket, during storms,\nChiara gave light."],
	"memory_10": ["Il buio faceva meno paura, in due.", "The dark was less scary, together."],
	"sc_prologue": ["Prologo", "Prologue"],
	"sc_finale": ["Finale", "Ending"],
	"sc_epilogue": ["Epilogo", "Epilogue"],
	"sc_after": ["Dopo il Mondo", "After World"],
}


func t(key: String) -> String:
	var e = STR.get(key)
	if e == null:
		return key
	return e[1] if Save.settings["lang"] == "en" else e[0]
