extends RefCounted
## Sprite in pixel art scritti come testo: ogni carattere è un colore della palette.
## Disegni originali fatti per questo gioco (vedi ASSETS.md).

const PAL := {
	"k": Color("1a1423"), "w": Color("ffffff"), "g": Color("9aa0b4"), "G": Color("555a6e"),
	"r": Color("d9534f"), "R": Color("8f2d3a"), "o": Color("f08a3c"), "y": Color("ffd65a"),
	"Y": Color("c9962e"), "l": Color("9bd65a"), "n": Color("3f9a4f"), "c": Color("7fd4ff"),
	"b": Color("3f6fd6"), "B": Color("24306e"), "p": Color("8a5fd0"), "P": Color("4a2a7a"),
	"m": Color("f08fc0"), "M": Color("c0407a"), "t": Color("f2c6a0"), "T": Color("8a5a36"),
	"d": Color("4a2f1f"), "s": Color("cfd6e6"), "v": Color("c9a8ff"), "e": Color("fff3b0"),
	"h": Color(1, 1, 0.8, 0.35), "q": Color("241c30"),
}

const SPR := {
	# ---------------------------------------------------------- oggetti
	"frag": [
		"...yy...",
		"..ywwy..",
		".ywwwyy.",
		"ywwyyyyY",
		"YyyyyyYY",
		".YyyyYY.",
		"..YyYY..",
		"...YY...",
	],
	"frag2": [
		"........",
		"...yy...",
		"..ywwy..",
		".ywwyyY.",
		".YyyyYY.",
		"..YyYY..",
		"...YY...",
		"........",
	],
	"secret": [
		".....pp.....",
		".....pp.....",
		"....pvvp....",
		"pppppvvppppp",
		".pvvvwwvvvp.",
		"..pvvwwvvp..",
		"...pvvvvp...",
		"..pvvppvvp..",
		"..pvp..pvp..",
		".pp......pp.",
	],
	"life": [
		".rr...rr..",
		"rwwr.rrrr.",
		"rwrrrrrrr.",
		"rrrrrrrrr.",
		".rrrrrrr..",
		"..rrrrr...",
		"...rrr....",
		"....r.....",
	],
	"heart": [
		".kk...kk.",
		"krrk.krrk",
		"kwrrkrrRk",
		"krrrrrrRk",
		".krrrrRk.",
		"..krrRk..",
		"...kRk...",
		"....k....",
	],
	"heart_off": [
		".kk...kk.",
		"kGGk.kGGk",
		"kGGGkGGGk",
		"kGGGGGGGk",
		".kGGGGGk.",
		"..kGGGk..",
		"...kGk...",
		"....k....",
	],
	"cp_off": [
		"............",
		"............",
		"............",
		"............",
		"....GGGG....",
		"...GggggG...",
		"...GggggG...",
		"....GGGG....",
		".TTTTTTTTTT.",
		"TddddddddddT",
		"TdTTTTTTTTdT",
		"TdTddddddTdT.G",
		"TdTTTTTTTTdTGG",
		"TddddddddddT.G",
		"TTTTTTTTTTTT",
		".d........d.",
	],
	"cp_on": [
		".....y......",
		"....yy.y....",
		".....y.yy...",
		".......y....",
		"....YYYY....",
		"...YyyyyY...",
		"...YywyyY...",
		"....YYYY....",
		".rrrrrrrrrr.",
		"rRRRRRRRRRRr",
		"rRyyyyyyyyRr",
		"rRyRRRRRRyRr.y",
		"rRyyyyyyyyRryy",
		"rRRRRRRRRRRr.y",
		"rrrrrrrrrrrr",
		".R........R.",
	],
	"switch_up": [
		"....rrrrrrrr....",
		"...rwrrrrrrrr...",
		"...rrrrrrrrrr...",
		".GGGGGGGGGGGGGG.",
		"GggggggggggggggG",
		"GGGGGGGGGGGGGGGG",
	],
	"switch_down": [
		"................",
		"................",
		"...llllllllll...",
		".GGGGGGGGGGGGGG.",
		"GggggggggggggggG",
		"GGGGGGGGGGGGGGGG",
	],
	"blade": [
		".....ss.s.....",
		"..s.ssssss.s..",
		"..ssssssssss..",
		".sssggggggss.s",
		"sssggGGGGggss.",
		".ssgGGkkGGgsss",
		"sssgGkwwkGgss.",
		".ssgGkwwkGgsss",
		"sssgGGkkGGgss.",
		".ssggGGGGggsss",
		"s.ssggggggsss.",
		"..ssssssssss..",
		"..s.ssssss.s..",
		".....s.ss.....",
	],
	"echo": [
		"...h...",
		"..hyh..",
		".hywyh.",
		"hywwwyh",
		".hywyh.",
		"..hyh..",
		"...h...",
	],
	"chiara": [
		"...hhhhhh...",
		"..hheeeehh..",
		".hheewweehh.",
		".heewwwweeh.",
		".heewkwkweh.",
		".hheewweehh.",
		"..hheeeehh..",
		"..hheeeehh..",
		".hheeeeeehh.",
		".heeeeeeeeh.",
		".heeewweeeh.",
		".hheeeeeehh.",
		"..hhe..ehh..",
		"...hh..hh...",
	],
	# Chiara adulta (scena finale), rivolta verso sinistra
	"chiara_adult": [
		"....qqqq....",
		"...qqGqqq...",
		"..qqGqqqqq..",
		"..qtttqqqq..",
		"..tkttqGqq..",
		"..ttttqGqq..",
		"..tmttqqqq..",
		"...ttqqqqq..",
		"...tt.qqqq..",
		"..eeeeeqqq..",
		".eeeeeeeqq..",
		".teeeeetqq..",
		".teeeeetqq..",
		".teyyyetqq..",
		".t.eeee.tq..",
		"...eeee..q..",
		"..eeeeee....",
		"..eeeeee....",
		".eeeeeeee...",
		".eeeeeeee...",
		".eeyeeyee...",
		"eeeeeeeeee..",
		"eeeyeeeyee..",
		"eeeeeeeeee..",
		"...t..t.....",
		"...t..t.....",
		"...t..t.....",
		"..yy..yy....",
	],
	# la ciliegia portafortuna di Chiara (scena dopo il Mondo 1)
	"cherry": [
		"......nn....",
		".....dnnn...",
		"....d.dn....",
		"...d...d....",
		"..d.....d...",
		".rrr...rrr..",
		"rwwrr.rwwrr.",
		"rwrrr.rwrrr.",
		"rrrrR.rrrrR.",
		"rrrRR.rrrRR.",
		".rRR...rRR..",
	],
	"hand": [
		"....ww......",
		"...wssw.....",
		"...wssw.....",
		"...wssw.....",
		"...wsswww...",
		"...wsswswww.",
		".wwwsswswsww",
		"wsswssssssww",
		"wsssssssssww",
		".wssssssssw.",
		"..wsssssssw.",
		"...wsssssw..",
		"...wwwwwww..",
	],
	"pause": [
		"ww.ww",
		"ww.ww",
		"ww.ww",
		"ww.ww",
		"ww.ww",
		"ww.ww",
	],
	# ---------------------------------------------------------- icone abilità
	"ic_scatto": [
		"..........",
		".y...y....",
		".yy..yy...",
		".yyy.yyy..",
		".yyyyyyyy.",
		".yyy.yyy..",
		".yy..yy...",
		".y...y....",
		"..........",
	],
	"ic_bolla": [
		"...cccc...",
		"..c....c..",
		".c.ww...c.",
		".c.w....c.",
		".c......c.",
		".c......c.",
		"..c....c..",
		"...cccc...",
		"..........",
	],
	"ic_gravita": [
		"..v.......",
		".vvv...v..",
		"vvvvv..v..",
		"..v....v..",
		"..v..vvvvv",
		"..v...vvv.",
		"..v....v..",
		"..........",
		"..........",
	],
	"ic_tempo": [
		".yyyyyyyy.",
		".y......y.",
		"..yyyyyy..",
		"...yyyy...",
		"....yy....",
		"...y..y...",
		"..y.yy.y..",
		".yyyyyyyy.",
		".yyyyyyyy.",
	],
	"ic_schianto": [
		"....mm....",
		"....mm....",
		"....mm....",
		".mmmmmmmm.",
		"..mmmmmm..",
		"...mmmm...",
		"....mm....",
		"m........m",
		".mmmmmmmm.",
	],
	"ic_riflesso": [
		".ww....cc.",
		".ww....cc.",
		"wwww..cccc",
		"wwww..cccc",
		".ww....cc.",
		".ww....cc.",
		"w..w..c..c",
		"w..w..c..c",
		"..........",
	],
	# ---------------------------------------------------------- proiettili
	"shot_ink": [
		".kkk.",
		"kBBBk",
		"kBbBk",
		"kBBBk",
		".kkk.",
	],
	"shot_bolt": [
		"..yy",
		".yy.",
		"yyy.",
		".yyy",
		"..yy",
		".yy.",
		"yy..",
		"y...",
	],
	"shot_seed": [
		".YY.",
		"YyyY",
		"YyyY",
		".YY.",
	],
	"shot_candy": [
		".mm.",
		"mwmm",
		"mmmM",
		".MM.",
	],
	"shot_ray": [
		".rr.",
		"rwwr",
		"rwwr",
		".rr.",
	],
	"shot_page": [
		"wwwwww",
		"wggggw",
		"wwwwww",
		"wgggww",
		"wwwwww",
		"wggggw",
		"wwwwww",
	],
	"guard": [
		"..k...k...k..",
		".ksk.ksk.ksk.",
		"ksssksssksssk",
	],
	# ---------------------------------------------------------- 1 Cameretta
	"soldatino": [
		"....kkkk....",
		"....kkkk....",
		"....kkkk....",
		"...yyyyyy...",
		"....tttt....",
		"....tktk....",
		"....tttt....",
		"...rrrrrr.s.",
		"..rrryrrr.s.",
		"..rrrrrrrts.",
		"..trrrrrr.T.",
		"....rrrr....",
		"....bbbb....",
		"....b..b....",
		"....b..b....",
		"...kk..kk...",
	],
	"pallina": [
		"...rrrrrr...",
		"..rrrwwrrr..",
		".rrrwwrrrrr.",
		"yyyyyyyyyyyy",
		"yykkyyyykkyy",
		"yykkyyyykkyy",
		"yyyyyyyyyyyy",
		"bbbbkkkkbbbb",
		".bbbbbbbbbb.",
		"..bbbbbbbb..",
		"...bbbbbb...",
	],
	"trottola": [
		"......kk......",
		"......yy......",
		"......yy......",
		"...rrrrrrrr...",
		".rrrrrrrrrrrr.",
		"yyyyyyyyyyyyyy",
		"bbwkbbbbbbwkbb",
		"bbbbbbbbbbbbbb",
		".llllllllllll.",
		"..llllllllll..",
		"...rrrrrrrr...",
		"....rrrrrr....",
		".....yyyy.....",
		"......kk......",
	],
	# ---------------------------------------------------------- 2 Prati di Nuvole
	"pecora": [
		"....wwww.www....",
		"..wwwwwwwwwww...",
		".wwwwwwwwwwwwkk.",
		"wwwwwwwwwwwwkkkk",
		"wwwwwwwwwwwwkwkk",
		"wwwwwwwwwwwwkkkk",
		".wwwwwwwwwwwwkk.",
		"..wwwwwwwwwww...",
		"...wwwwwwwww....",
		"...k..k..k.k....",
		"...k..k..k.k....",
	],
	"nuvoletta": [
		"....GGGG..GGG...",
		"..GGggggGGgggG..",
		".GggggggggggggG.",
		"GggkkggggggkkggG",
		"GgggwkggggkwgggG",
		"GggggggkkggggggG",
		".GggggggggggggG.",
		"..GGGGGGGGGGGG..",
		"......y...y.....",
	],
	"grandine": [
		"..cccc..",
		".cwwccc.",
		"cwwccccc",
		"cwcccccb",
		"ccccccbb",
		"cccccbbb",
		".cccbbb.",
		"..bbbb..",
	],
	# ---------------------------------------------------------- 3 Biblioteca
	"libro": [
		"..RRRRRRRRRRRR",
		".RrrrrrrrrrrrR",
		"RrrrryyrrrrrrR",
		"RrrrrrrrrkwrrR",
		"RrrrrrrrrkkrrR",
		"RwkwkwkwkwkwkR",
		".............R",
		"RwkwkwkwkwkwkR",
		"RttttttttttttR",
		"RttttttttttttR",
		".RRRRRRRRRRRRR",
	],
	"segnalibro": [
		"rrrrrrrr",
		"rRRRRRRr",
		"rRrrrrRr",
		"rRrkrkRr",
		"rRrrrrRr",
		"rRrkkrRr",
		"rRrrrrRr",
		"rRrrrrRr",
		"rRrrrrRr",
		"rRrrrrRr",
		"rRrrrrRr",
		"rRr..rRr",
		"rr....rr",
		"r......r",
	],
	"calamaio": [
		"....kkkk....",
		"....kBBk....",
		"...kkBBkk...",
		"..kkkkkkkk..",
		".kBBBBBBBBk.",
		"kBBwkBBwkBBk",
		"kBBkkBBkkBBk",
		"kBBBBBBBBBBk",
		"kBBBkkkkBBBk",
		"kBbBBBBBBbBk",
		".kBBBBBBBBk.",
		"..kkkkkkkk..",
	],
	# ---------------------------------------------------------- 4 Oceano di Stelle
	"medusa": [
		"...cccccc...",
		"..cwwccccc..",
		".cwwcccccccc",
		".ccckcckcccc",
		".cccccccccc.",
		".cccccccccc.",
		"..c.cc.cc.c.",
		"..c.c..c..c.",
		".c..c..c...c",
		".c...c..c..c",
		"..y..y..y.y.",
		"...y...y....",
	],
	"pesce": [
		"..........yy....",
		".........y..y...",
		"....BBBBBB..e...",
		"B..BbbbbbbBB....",
		"BB.BbbbbwkbbB...",
		"BBBbbbbbkkbbbB..",
		"BB.BbbbbbbbwwB..",
		"B..BbbbbbbwkB...",
		"....BBBBBBBB....",
	],
	"stella": [
		"....yy....",
		"....yy....",
		"...ywwy...",
		"yyyywwyyyy",
		".yywwwwyy.",
		"..ywwwwy..",
		"..yyyyyy..",
		".yyy..yyy.",
		".yy....yy.",
	],
	# ---------------------------------------------------------- 5 Città Capovolta
	"lampione": [
		"..GGGG..",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"...GG...",
		"..GGGG..",
		".GkyykG.",
		".GyyyyG.",
		".GykkyG.",
		".GyyyyG.",
		"..GyyG..",
		"...ee...",
		"..eeee..",
	],
	"piccione": [
		"...GGGG.....",
		"..GggggGG...",
		".GggkwgggG..",
		"oGgggggggGG.",
		".GggppgggggG",
		"..GggggggggG",
		"...GGggggGG.",
		".....o.o....",
		".....o.o....",
	],
	"tombino": [
		"................",
		"................",
		"................",
		"................",
		".GGGGGGGGGGGGGG.",
		"GgGgGgGgGgGgGgGG",
		"GGgGgGgGgGgGgGgG",
		".GGGGGGGGGGGGGG.",
	],
	"tombino_o": [
		"...p......p.....",
		"..p..p..p...p...",
		".p.pkkkkkkkp.p..",
		"..pkkPPPPkkp....",
		".GGkPPrPPrPkGGG.",
		"GgGkPPPPPPPkgGGG",
		"GGgkkPPkkPPkGgGG",
		".GGGkkkkkkkGGGG.",
	],
	# ---------------------------------------------------------- 6 Orologeria
	"ingranaggio": [
		"....YY..YY....",
		"....YY..YY....",
		"..YYYYYYYYYY..",
		"..YyyyyyyyyY..",
		"YYYyykyykyyYYY",
		"YYYyykyykyyYYY",
		"..YyyyyyyyyY..",
		"..YyykkkkyyY..",
		"YYYyyyyyyyyYYY",
		"YYYyyyyyyyyYYY",
		"..YyyyyyyyyY..",
		"..YYYYYYYYYY..",
		"....YY..YY....",
		"....YY..YY....",
	],
	"cucu": [
		".....TT.....",
		"....TddT....",
		"...TddddT...",
		"..TddddddT..",
		".TTTTTTTTTT.",
		".TdwwwwwwdT.",
		".TdwkwwkwdT.",
		".TdwwwwwwdT.",
		".TdwwkkwwdT.",
		".TdddddddddT",
		".TdkkkkkkdT.",
		".TdkyykkkdT.",
		".TdkkkkkkdT.",
		".TTTTTTTTTT.",
		"...Y....Y...",
		"...Y....Y...",
	],
	"pendolo": [
		"...YYYYYY...",
		"..YyyyyyyY..",
		".YyywwyyyyY.",
		"YyywyyyyyyyY",
		"YyyyyyyyyyyY",
		"YyyykyykyyyY",
		"YyyyyyyyyyyY",
		"YyyyykkyyyyY",
		".YyyyyyyyyY.",
		"..YyyyyyyY..",
		"...YYYYYY...",
	],
	# ---------------------------------------------------------- 7 Regno dei Dolci
	"gommoso": [
		".ll......ll.",
		"llll....llll",
		"llllllllllll",
		"llwkllllwkll",
		"llkkllllkkll",
		"llllllllllll",
		"lllllkklllll",
		"nllllllllllnn",
		".nllllllllnn.",
		"..nnnnnnnnn.",
	],
	"cupcake": [
		".....rr.....",
		"....mmmm....",
		"...mwmmmm...",
		"..mmmmmmmm..",
		".mmmmmmmmmm.",
		"mmkwmmmmkwmm",
		"mmkkmmmmkkmm",
		".mmmmkkmmmm.",
		"TTTTTTTTTTTT",
		".TtTtTtTtTT.",
		".TtTtTtTtTT.",
		"..TtTtTtTT..",
		"..TTTTTTTT..",
	],
	"caramella": [
		"M.............M",
		"MM..mmmmmmm..MM",
		"MMMmmwwmmmmmMMM",
		"MMmmkwmmmkwmmMM",
		"MMmmkkmmmkkmmMM",
		"MMMmmmmmmmmmMMM",
		"MM..mmmkkmm..MM",
		"M....mmmmm....M",
		"...m..m..m.m...",
		"..m..m..m...m..",
	],
	# ---------------------------------------------------------- 8 Sala degli Specchi
	"vetro": [
		"....ss....",
		"...scws...",
		"..sccwcs..",
		".sccccwcs.",
		"sckcckcccs",
		".sccccccs.",
		"..scccccs.",
		"...sccs...",
		"....ss....",
	],
	"specchio": [
		"...YYYYYY...",
		"..YccccccY..",
		".YcwwccccvY.",
		".YcwccccvvY.",
		".YcckcckvvY.",
		".YccccccvvY.",
		".YcccccvvvY.",
		".YcckkkcvvY.",
		".YccccvvvvY.",
		".YcccvvvvvY.",
		".YccvvvvvvY.",
		"..YvvvvvvY..",
		"...YYYYYY...",
		"....YYYY....",
		"...YYYYYY...",
	],
	# ---------------------------------------------------------- 9 Tempesta
	"corvo": [
		"......kkkk....",
		".kk..kkkkkk...",
		"kkkkkkkwkkkyy.",
		".kkkkkkkkkkk..",
		"..kkkkkkkkk...",
		"...kkkkkkk....",
		"..kkk.kkk.....",
		".kk...kk......",
	],
	"ombrello": [
		".....rrrr.....",
		"...rrrrrrrr...",
		"..rrRrrrrRrr..",
		".rrrRrrrrRrrr.",
		"rrrrRrrrrRrr.r",
		"r..r..kk..r...",
		"......kk......",
		"......kk......",
		"......kk......",
		"......kk..k...",
		"......kkkkk...",
	],
	# ---------------------------------------------------------- 10 Incubo
	"mano": [
		"..P..P.P..",
		".PP.PP.PP.",
		".PP.PP.PPP",
		".PPkPPkPPP",
		"PPPPPPPPPP",
		"PPPPPPPPPP",
		"PPPrPPrPPP",
		".PPPPPPPP.",
		".PPPPPPPP.",
		"..PPPPPP..",
		"..PPPPPP..",
		"..PPPPPP..",
		"..PPPPPP..",
		"..kPPPPk..",
		".kkPPPPkk.",
		"kkkkkkkkkk",
	],
	"occhio": [
		"....PPPPPP....",
		"..PPwwwwwwPP..",
		".PwwwwrrwwwwP.",
		"PwwwwrrrrwwwwP",
		"PwwwrrkkrrwwwP",
		"PwwwrrkkrrwwwP",
		"PwwwwrrrrwwwwP",
		".PwwwwrrwwwwP.",
		"..PPwwwwwwPP..",
		"....PPPPPP....",
		"..P..P..P..P..",
	],
}
